"""empty message

Revision ID: 199ebaeb89d0
Revises: 
Create Date: 2023-04-21 11:11:23.777472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199ebaeb89d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('s3_path', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('s3_path', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=200), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['oauth_id'], ['oauth_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_id', 'asset_id')
    )
    op.create_table('user_container',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'container_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_container')
    op.drop_table('user')
    op.drop_table('script')
    op.drop_table('oauth_service')
    op.drop_table('container')
    # ### end Alembic commands ###
