"""empty message

Revision ID: 4f87b3a307f4
Revises: a36afbf9e59f
Create Date: 2023-04-20 13:33:08.807029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f87b3a307f4'
down_revision = 'a36afbf9e59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['oauth_id', 'asset_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('asset_id')

    # ### end Alembic commands ###
